version: '3.5'

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    networks:
      - drone
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true


networks:
  drone:
    name: drone_network
