version: '3.5'

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    networks:
      - drone
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    env_file:
      - ./drone.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST={DRONE_SERVER_HOST}
      - DRONE_RPC_PROTO=https
      - DRONE_RUNNER_NETWORKS=drone
      - DRONE_RUNNER_CAPACITY=8
networks:
  drone:
    name: drone_network
